### ISSUE TITLE
Is there any point of endianness swap for floats and doubles?

### ISSUE THREAD

**Issue by slavanap** [orocos-toolchain/typelib#111]
https://github.com/orocos-toolchain/typelib/blob/master/typelib/endianness.hh#L27-L28

On the contrary, endianness for floating point values might be mixed on several architectures:
https://en.wikipedia.org/wiki/Endianness#Floating_point

**Comment by doudou** [comment]
I'm personally interpreting 

```
However, on modern standard computers (i.e., implementing IEEE 754), one may in practice safely assume that the endianness is the same for floating-point numbers as for integers, making the conversion straightforward regardless of data type.
```

as "do it by default".
