### ISSUE TITLE
Ruby 2.7 bindings fail to compile in memory module in Ubuntu `focal`

### ISSUE THREAD

**Issue by spd-intermodalics** [orocos-toolchain/typelib#130]
When I was trying to compile `typelib` for Ubuntu focal with its dependencies, I encountered this error, related with PR #126.

```
src/orocos_toolchain/typelib/bindings/ruby/ext/memory.cc:34:5: error: invalid conversion from ‘int (*)(...)’ to ‘int (*)(st_data_t, st_data_t)’ {aka ‘int (*)(long unsigned int, long unsigned int)’} [-fpermissive]
   34 |     (int (*)(...))memory_table_compare,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     |
      |     int (*)(...)
/build/src/orocos_toolchain/typelib/bindings/ruby/ext/memory.cc:35:5: error: invalid conversion from ‘st_index_t (*)(...)’ {aka ‘long unsigned int (*)(...)’} to ‘st_index_t (*)(st_data_t)’ {aka ‘long unsigned int (*)(long unsigned int)’} [-fpermissive]
   35 |     (st_index_t (*)(...))memory_table_hash
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     |
      |     st_index_t (*)(...) {aka long unsigned int (*)(...)}
```

**Comment by doudou** [comment]
I'm guessing that this is not master ? `master` already has a fix for it.

**Comment by spd-intermodalics** [comment]
You are right, I was using the branch `toolchain-2.9`, which still had the bug, when compiling using `master` it succeeds, so I guess I can close the issue.

**Comment by meyerj** [comment]
> You are right, I was using the branch `toolchain-2.9`, which still had the bug, when compiling using `master` it succeeds, so I guess I can close the issue.

But we should keep the `toolchain-2.9` branch up-to-date by merging all changes from `master`. It should track `master` but additionally includes some patches to build with catkin or release into ROS that are not acceptable to be applied on `master`. Of course ideally we could just use `master` directly.

At the moment the diff is https://github.com/orocos-toolchain/typelib/compare/master...toolchain-2.9. Some of the patches might even be applied to `master`, too, for example the installation of `package.xml` and the removal of outdated `Makefile`. Others are probably invalid and should be reverted, like https://github.com/orocos-toolchain/typelib/commit/c01a6c1e839bc8baa4fa74278d1bcde266285a0d.
