### ISSUE TITLE
GCCXML not available on 18.04 and newer

### ISSUE THREAD

**Issue by MatthijsBurgh** [orocos-toolchain/typelib#132]
[GCCXML](https://github.com/gccxml/gccxml) has been discontinued. It has been replaced by [CastXML](https://github.com/CastXML/CastXML).

Could you implement CastXML?

**Comment by doudou** [comment]
castxml support exists in typelib for years. However, nobody ever bothered to make it the default loader (which it should have been since 16.04, probably).

Set the TYPELIB_CXX_LOADER environment variable to castxml.

**Comment by MatthijsBurgh** [comment]
@doudou should we make castxml the default? And remove the dependency on gccxml from package.xml? 
I can open a PR to do it.

**Comment by doudou** [comment]
Sure, that would be nice
