### ISSUE TITLE
Memory leak in typelib container type

### ISSUE THREAD

**Issue by saarnold** [orocos-toolchain/typelib#31]
While converting old to new types using the rock log converter, I stumbled over a possible memory leak. Apparently it happens when elements are added to a std/vector container. This small script reveals the problem:

```ruby
require 'orocos'
require 'readline'
include Orocos
Orocos.initialize

def create_objects(typename, object_count, element_count)
    registry = Orocos.registry
    object_count.times { 
        puts "Create new object"
        type = registry.get(typename).new 
        element_count.times { type.ranges.push 0 }
        #element_count.times { type.ranges.do_push 0 }

        size = `ps -o rss -p #{$$}`.chomp.split("\n").last.to_i / 1024
        puts "Memory usage: " + size.to_s + " MB"
        puts "Object losses reference"
    }
end

type_name = '/base/samples/LaserScan'
Orocos.load_typekit_for type_name

size = `ps -o rss -p #{$$}`.chomp.split("\n").last.to_i / 1024
puts "Memory usage start: " + size.to_s + " MB"

create_objects(type_name, 10, 100000)

#Manually run GC
GC.start

size = `ps -o rss -p #{$$}`.chomp.split("\n").last.to_i / 1024
puts "Memory usage end: " + size.to_s + " MB"

puts "Press enter to exit."
Readline.readline
```
Using the direct c binding do_push works perfectly fine. Using push is way slower and the GC does not free all objects. 

So when converting log files my complete memory runs full. Currently I'm using an FFI::MemoryPointer and raw_memcpy to tackle the problem.

PS: I'm using 14.04 and the master branch.

**Comment by doudou** [comment]
Can you give more information about the memory figures as well as ruby version(s) ? On 2.1 I get a RSS increase of 15MB (88MB to 103MB) while the script allocates around 42MB (so, no leak it seems). The RSS before GC.start is the same, so it was unneeded in my case.

**Comment by doudou** [comment]
About the speed: there is very likely a performance hit of one against the other. #push and other related methods currently get through a generic code path that makes them be a lot slower than they could be for simple cases. People willing to optimize are welcome !

**Comment by saarnold** [comment]
Im using ruby 1.9.3p484, default current on Ubuntu 14.04
I changed the example script above a bit to give out the memory usage in each step.
On my mashine the result looks like this:
```
Memory usage start: 56 MB
Create object
Memory usage: 66 MB
Delete object
Create object
Memory usage: 69 MB
Delete object
Create object
Memory usage: 72 MB
Delete object
Create object
Memory usage: 76 MB
Delete object
Create object
Memory usage: 79 MB
Delete object
Create object
Memory usage: 81 MB
Delete object
Create object
Memory usage: 85 MB
Delete object
Create object
Memory usage: 88 MB
Delete object
Create object
Memory usage: 92 MB
Delete object
Create object
Memory usage: 95 MB
Delete object
Memory usage end: 95 MB
Press enter to exit.
```
The manual call of the GC doesn't change anything, thats true.

When using do_push instead of push, the result looks like this:
```
Memory usage start: 56 MB
Create new object
Memory usage: 56 MB
Object losses reference
Create new object
Memory usage: 57 MB
Object losses reference
Create new object
Memory usage: 57 MB
Object losses reference
Create new object
Memory usage: 57 MB
Object losses reference
Create new object
Memory usage: 58 MB
Object losses reference
Create new object
Memory usage: 58 MB
Object losses reference
Create new object
Memory usage: 58 MB
Object losses reference
Create new object
Memory usage: 59 MB
Object losses reference
Create new object
Memory usage: 59 MB
Object losses reference
Create new object
Memory usage: 60 MB
Object losses reference
Memory usage end: 56 MB
Press enter to exit.
```
In this case the manual call of the GC seems to help also.

**Comment by saarnold** [comment]
Your fix works perfectly fine. Thanks!

**Comment by doudou** [comment]
One thing about performance: if you could use the FFI/raw_memcpy workaround, it means that rock-convert should be using Typelib.copy instead of iterating over the elements.
