### ISSUE TITLE
Segfault for structs of size 3

### ISSUE THREAD

**Issue by dseifert-as** [orocos-toolchain/typelib#55]
In MemLayout::Visitor::apply the removing of trailing skips is assuming that
the second-to-last element in ops is a flag. This fails if it is not but has
a value that resembles one.

Example: 0x2 (FLAG_CONTAINER) 0x361ad80 (ptr) 0x0 (FLAG_MEMCPY) 0x3 (MEMCPY
byte count) 0x4 (FLAG_END)

Here the byte count value (0x3) for FLAG_MEMCPY is interpreted as FLAG_SKIP,
causing ops to be truncated to 0x2 0x361ad80 0x0. Subsequently,
MemLayout::Visitor::merge_skips_and_copies goes beyond ops.end(), preventing
the loop to exit and causing a segmentation fault. 

Reproduction steps:

example.orogen

	name "example"
	import_types_from "DataPoint.h"

DataPoint.h

	#include <vector>

	struct DataPoint {
		char x, y, z;
	};

	struct DataPointCollection {
		std::vector<DataPoint> points;
	};

and call "orogen example.orogen"

**Comment by doudou** [comment]
This is actually fixed for a long while now ...
