### ISSUE TITLE
why pcl::PCLPointCloud2 is not typelib compatible

### ISSUE THREAD

**Issue by saarnold** [orocos-toolchain/typelib#73]
I had a short look on the issue why the PCLPointCloud2 type is not typelib compatible.
Using it on ports and logging it seems to work, the problem occurs when using the typelib type in ruby. The issue is that it has a field which is called 'fields' and is a compound type. Compound types also have a member variable with the same name. So the return of `instance_variable_get("@#{field_name}")` is not the expected in case the field name is 'fields'.

One possible solution would be to rename the `@fields` member, but this would also affect orogen and vizkit and most likely other components and would not avoid that this problem happens again.

The better solution I think would be extending the names of the fields that are accessed by instance_variable_get or instance_variable_set by a name suffix. I already did this and it works for this case.
The question is if this would be the right solution here? 
If yes I'll create a PR for this issue.

**Comment by doudou** [comment]
You're right, you would need to prefix all instance variables at the instance level with e.g. `__typelib_` to avoid clashes. It is definitely the best fix.

Just make sure you touch the instance, not the class level (i.e. object and instance methods, not singleton methods)
