### ISSUE TITLE
link error on macOS sierra

### ISSUE THREAD

**Issue by ahoarau** [orocos-toolchain/typelib#98]
```
Undefined symbols for architecture x86_64:
  "_rb_ary_new2", referenced from:
      compound_get_fields(unsigned long) in specialized_types.cc.o
  "_rb_data_object_alloc", referenced from:
      typelib_ruby::cxx2rb::type_wrap(Typelib::Type const&, unsigned long) in value.cc.o
      value_alloc(unsigned long) in value.cc.o
      value_create_empty(unsigned long) in value.cc.o
      registry_alloc(unsigned long) in registry.cc.o
      registry_minimal(unsigned long, unsigned long, unsigned long) in registry.cc.o
      typelib_ruby::memory_wrap(void*, bool, void*) in memory.cc.o
      typelib_ruby::Typelib_init_memory() in memory.cc.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
``` 

* macOS Sierra
* ruby 2.4.0

**Comment by doudou** [comment]
I do apologize, but since I don't have access to a setup even remotely looking like this there's not much I'll be able to do.

This looks like a problem with the ruby shared library.... More than that I don't know. If you have installed ruby using rbenv/rvm make sure that it was configured with `--enable-shared`

**Comment by ahoarau** [comment]
ok I think I see what's happening here, the include dirs are wrong, but it's finding the right library.
Look at `RUBY_INCLUDE_DIRS` (I tried with 1.9.3 just to test): 
```
RUBY_LIBRARY --> /Users/hoarau/.rvm/rubies/ruby-1.9.3-p551/lib/libruby.1.9.1.dylib
RUBY_LIBRARY_INSTALL_DIR-->lib/ruby/1.9.1
RUBY_INCLUDE_DIRS-->/System/Library/Frameworks/Ruby.framework/Headers;/System/Library/Frameworks/Ruby.framework/Headers;/System/Library/Frameworks/Ruby.framework/Headers
```

I managed to compile typelib with the following patch on `FindRuby.cmake`: 
```cmake 
diff --git a/cmake/FindRuby.cmake b/cmake/FindRuby.cmake
index 0faf0df..3cc5e50 100644
--- a/cmake/FindRuby.cmake
+++ b/cmake/FindRuby.cmake
@@ -181,11 +181,14 @@ IF(Ruby_FIND_VERSION)
    ENDIF(${RUBY_VERSION}  VERSION_LESS  ${Ruby_FIND_VERSION})
 ENDIF(Ruby_FIND_VERSION)

-FIND_PATH(RUBY_INCLUDE_DIR
-   NAMES ruby.h
-   HINTS
-   ${RUBY_HDR_DIR}
-   ${RUBY_ARCH_DIR})
+EXECUTE_PROCESS(COMMAND ${RUBY_EXECUTABLE} -r rbconfig -e "print RbConfig::CONFIG['includedir']"
+OUTPUT_VARIABLE RUBY_INCLUDE_DIR_PATH)
+set(RUBY_INCLUDE_DIR ${RUBY_INCLUDE_DIR_PATH}/ruby-${RUBY_VERSION_MAJOR}.${RUBY_VERSION_MINOR}.${RUBY_VERSION_PATCH})
+# FIND_PATH(RUBY_INCLUDE_DIR
+#    NAMES ruby.h
+#    HINTS
+#    ${RUBY_HDR_DIR}
+#    ${RUBY_ARCH_DIR})
 set(RUBY_INCLUDE_DIRS ${RUBY_INCLUDE_DIR})

 # if ruby > 1.8 is required or if ruby > 1.8 was found, search for the config.h dir
@@ -193,10 +196,11 @@ IF( ${Ruby_FIND_VERSION_SHORT_NODOT} GREATER 18  OR  ${_RUBY_VERSION_SHORT_NODOT
    message(STATUS "FindRuby: looking for config.h")
    FIND_PATH(RUBY_CONFIG_INCLUDE_DIR
      NAMES ruby/config.h  config.h
-     HINTS
+     HINTS
+     ${RUBY_INCLUDE_DIR}
      ${RUBY_HDR_DIR}/${RUBY_ARCH}
      ${RUBY_ARCH_HDR_DIR}
-     ${RUBY_ARCH_DIR}
+     ${RUBY_ARCH_DIR}
      )

    list(APPEND RUBY_INCLUDE_DIRS ${RUBY_INCLUDE_DIRS} ${RUBY_CONFIG_INCLUDE_DIR})

```

And it outputs : 
```
RUBY_LIBRARY --> /Users/hoarau/.rvm/rubies/ruby-2.4.0/lib/libruby.2.4.0.dylib
RUBY_LIBRARY_INSTALL_DIR-->lib/ruby/2.4.0
RUBY_INCLUDE_DIRS-->/Users/hoarau/.rvm/rubies/ruby-2.4.0/include/ruby-2.4.0;/Users/hoarau/.rvm/rubies/ruby-2.4.0/include/ruby-2.4.0;/System/Library/Frameworks/Ruby.framework/Headers
```

As soon as we have the binary `ruby`, aren't all the configuration paths you need accessible directly with the rbconfig tool ? Why is there a need for `find_path` and `find_library`?

**Comment by ahoarau** [comment]
Same on another machine (also on sierra)

**Comment by doudou** [comment]
> As soon as we have the binary ruby, aren't all the configuration paths you need accessible directly with the rbconfig tool ? Why is there a need for find_path and find_library?

This is actually a very good question. I'm sorry it takes a bit long, I'll try to get a deeper look this week

**Comment by ahoarau** [comment]
No problem. To add more info, first machine's Ruby was installed with `rvm`, second using `brew`.

**Comment by ahoarau** [comment]
@doudou Did you get a chance to look into this issue ? Thanks !

**Comment by doudou** [comment]
Sorry, I forgot about it.

The real question for me now is: why do we even still have our own FindRuby... Would you mind removing this file (thus using the FindRuby from CMake) and checking if that would fix your problem ?

**Comment by ahoarau** [comment]
It worked !
I removed `FindRuby.cmake`and `FindBoost.cmake` as well.
I have `cmake version 3.8.2` (the one included in brew), which is not the case for ubuntu 14 nor 16, so the `FindRuby.cmake` might have changed between two versions.
Could you also try on your linux machine ?

**Comment by ahoarau** [comment]
Working on a 16.04 machine as well :+1:
